---
title: "My Growth as a Data Scientist"
format: html
editor: visual
author: "Elizabeth Scholtes"
---

I have improved as a practitioner and student of data science through the work this whole quarter. One of the biggest things that I learned was how to write tidy and efficient code. This improvement can be seen throughout the quarter in my improvement of using the filter function only once rather than calling it multiple times to do multiple filters. This can be seen in Lab 3when I only use the filter function once in each pipe. In my first attempt of the lab, I called the filter function at least 3 times in the same pipe.

A second concept that I am proud of is learning how to use pivots, or more broadly, working with data. This is very important in learning how to work with data because most of the time, raw data does not come in a format that can be used right away. Being able to pivot data is crucial in data analysis. I showed my proficiency in pivots starting in Lab 4 Question **7** but continued to show my proficiency the rest of the quarter and even used it in the last lab, Lab 9 Questions 2 & 11.

A final concept that I am proud of is creating readable and useful data visualizations with ggplot. I showed this in Lab 7where I created a simple plot in question 3 that had descriptive labels, a facet wrap, and multiple defined aesthetics.

Something else that I learned as a data scientist is to recognize the hard work and effort I put in to assignments and class. I discussed this topic briefly in my final reflection. In my midterm reflection meeting, we talked about the difference between earning something and deserving something. This truly has made an impact on the way that I view things. It is important as a data scientist and as a person to recognize that hard work earns you something, and nobody can take that away from you.
